DEBUG 2025-05-21 14:14:48.047 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-21 14:14:48.048 UTC: 	 Running on: Linux pcwaw09 5.14.0-503.23.2.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 12 05:52:18 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-21 14:14:48.048 UTC: 	 Using SINGULARITY image: el9:x86_64
DEBUG 2025-05-21 14:14:48.048 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-05-21 14:14:48.048 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-21 14:14:48.048 UTC: 	 Could not find CRAB cache file /home/psajdak/.crab3; creating a new one.
INFO 2025-05-21 14:14:48.049 UTC: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2025-05-21 14:14:48.049 UTC: 	 Loading CRAB configuration file.
ERROR 2025-05-21 14:14:48.077 UTC: 	 Invalid CRAB configuration: Parameter JobType.pluginName has an invalid value ('Analysis_cwPS').
Allowed values are: ANALYSIS, PRIVATEMC, COPYCAT, RECOVER.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-05-21 14:14:48.077 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: Parameter JobType.pluginName has an invalid value ('Analysis_cwPS').
Allowed values are: ANALYSIS, PRIVATEMC, COPYCAT, RECOVER.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-05-21 14:14:48.080 UTC: 	 Log file is /eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/jobs/crab.log
DEBUG 2025-05-21 14:16:49.119 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-21 14:16:49.119 UTC: 	 Running on: Linux pcwaw09 5.14.0-503.23.2.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 12 05:52:18 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-21 14:16:49.119 UTC: 	 Using SINGULARITY image: el9:x86_64
DEBUG 2025-05-21 14:16:49.119 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-05-21 14:16:49.119 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-21 14:16:49.119 UTC: 	 Found CRAB cache file /home/psajdak/.crab3
INFO 2025-05-21 14:16:49.119 UTC: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2025-05-21 14:16:49.119 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-21 14:16:49.141 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-21 14:16:49.143 UTC: 	 Working area '/eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/jobs/qqq2/crab_hhhhhh2' already exists 
Please change the requestName in the config file
ERROR 2025-05-21 14:16:49.143 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/jobs/qqq2/crab_hhhhhh2' already exists 
Please change the requestName in the config file
INFO 2025-05-21 14:16:49.148 UTC: 	 Log file is /eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/jobs/crab.log
DEBUG 2025-05-25 12:29:43.045 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-25 12:29:43.045 UTC: 	 Running on: Linux pcwaw09 5.14.0-503.23.2.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 12 05:52:18 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-25 12:29:43.045 UTC: 	 Using SINGULARITY image: el9:x86_64
DEBUG 2025-05-25 12:29:43.045 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-05-25 12:29:43.045 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-25 12:29:43.045 UTC: 	 Found CRAB cache file /home/psajdak/.crab3
INFO 2025-05-25 12:29:43.046 UTC: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2025-05-25 12:29:43.046 UTC: 	 Loading CRAB configuration file.
ERROR 2025-05-25 12:29:43.079 UTC: 	 Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 100 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-05-25 12:29:43.079 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 100 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-05-25 12:29:43.081 UTC: 	 Log file is /eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/jobs/crab.log
DEBUG 2025-05-25 21:15:07.506 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-25 21:15:07.506 UTC: 	 Running on: Linux pcwaw09 5.14.0-503.23.2.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 12 05:52:18 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-25 21:15:07.506 UTC: 	 Using SINGULARITY image: el9:x86_64
DEBUG 2025-05-25 21:15:07.506 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-05-25 21:15:07.506 UTC: 	 Executing command: 'kill'
DEBUG 2025-05-25 21:15:07.506 UTC: 	 Found CRAB cache file /home/psajdak/.crab3
ERROR 2025-05-25 21:15:07.506 UTC: 	 Error: Please indicate the CRAB project directory with --dir=<project-directory>.
ERROR 2025-05-25 21:15:07.506 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 687, in validateOptions
    raise ex
CRABClient.ClientExceptions.MissingOptionException: [91mError[0m: Please indicate the CRAB project directory with --dir=<project-directory>.
INFO 2025-05-25 21:15:07.511 UTC: 	 Log file is /eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/jobs/crab.log
DEBUG 2025-05-25 21:44:44.874 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-25 21:44:44.874 UTC: 	 Running on: Linux pcwaw09 5.14.0-503.23.2.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 12 05:52:18 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-25 21:44:44.874 UTC: 	 Using SINGULARITY image: el9:x86_64
DEBUG 2025-05-25 21:44:44.874 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-05-25 21:44:44.874 UTC: 	 Executing command: 'kill'
DEBUG 2025-05-25 21:44:44.874 UTC: 	 Found CRAB cache file /home/psajdak/.crab3
ERROR 2025-05-25 21:44:44.876 UTC: 	 Error: /eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/jobs/JpsiK/crab_quickTest is not a valid CRAB project directory.
ERROR 2025-05-25 21:44:44.876 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: /eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/jobs/JpsiK/crab_quickTest is not a valid CRAB project directory.
INFO 2025-05-25 21:44:44.879 UTC: 	 Log file is /eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/jobs/crab.log
DEBUG 2025-05-25 21:47:09.221 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-25 21:47:09.222 UTC: 	 Running on: Linux pcwaw09 5.14.0-503.23.2.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 12 05:52:18 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-25 21:47:09.222 UTC: 	 Using SINGULARITY image: el9:x86_64
DEBUG 2025-05-25 21:47:09.222 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-05-25 21:47:09.222 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-25 21:47:09.222 UTC: 	 Found CRAB cache file /home/psajdak/.crab3
DEBUG 2025-05-25 21:57:29.726 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-25 21:57:29.726 UTC: 	 Running on: Linux pcwaw09 5.14.0-503.23.2.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 12 05:52:18 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-25 21:57:29.726 UTC: 	 Using SINGULARITY image: el9:x86_64
DEBUG 2025-05-25 21:57:29.726 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-05-25 21:57:29.726 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-25 21:57:29.726 UTC: 	 Found CRAB cache file /home/psajdak/.crab3
INFO 2025-05-25 21:57:29.739 UTC: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2025-05-25 21:57:29.739 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-25 21:57:29.759 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-25 21:57:29.759 UTC: 	 Working area '/eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/jobs/Jpsi_K/crab_full0' already exists 
Please change the requestName in the config file
ERROR 2025-05-25 21:57:29.759 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/jobs/Jpsi_K/crab_full0' already exists 
Please change the requestName in the config file
INFO 2025-05-25 21:57:29.761 UTC: 	 Log file is /eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/jobs/crab.log
DEBUG 2025-05-26 10:31:39.401 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-26 10:31:39.401 UTC: 	 Running on: Linux pcwaw09 5.14.0-503.23.2.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 12 05:52:18 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-26 10:31:39.401 UTC: 	 Using SINGULARITY image: el9:x86_64
DEBUG 2025-05-26 10:31:39.401 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-05-26 10:31:39.401 UTC: 	 Executing command: 'status'
DEBUG 2025-05-26 10:31:39.401 UTC: 	 Found CRAB cache file /home/psajdak/.crab3
